version: '3.8'

services:

  web-image:
    build:
      context: ./web
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - fastapi-app
      - mysql-db
    networks:
      - app-network

  fastapi-app:
    build:
      context: ./api
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    networks:
      - app-network


  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: students_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pswrd
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
  

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local

